services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7-alpine

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/portfolio
      - CACHE_URL=redis://redis:6379/1
      - BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      
    depends_on:
      - db
      - redis

volumes:
  postgres_data: